// Downloads the HUD typefaces from Google Fonts once and writes src/app/fonts/fonts.css plus the woff2
// files next to it, so dev, static export and GitHub Pages no longer depend on fonts.googleapis.com
// at build time. Re-run to refresh: `node scripts/fetch-fonts.mjs`.
import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const FAMILIES = [
  { family: 'Orbitron', weights: [500, 700], variable: '--font-display' },
  { family: 'Rajdhani', weights: [500, 600], variable: '--font-label' },
  { family: 'Share Tech Mono', weights: [400], variable: '--font-mono' },
  { family: 'Noto Sans KR', weights: [500], variable: '--font-korean' },
];
// A modern Chrome UA makes Google answer with woff2 faces split by unicode-range.
const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36';
const OUT_DIR = join('src', 'app', 'fonts');
const FILES_DIR = join(OUT_DIR, 'files');

const slug = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function fetchText(url) {
  const response = await fetch(url, { headers: { 'user-agent': USER_AGENT } });
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return response.text();
}
async function fetchBytes(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

/** Parse Google's CSS into faces, keeping the `/* subset *\/` comment that precedes each block. */
function parseFaces(css) {
  const faces = [];
  const pattern = /(?:\/\*\s*([^*]+?)\s*\*\/\s*)?@font-face\s*{([^}]*)}/g;
  for (const match of css.matchAll(pattern)) {
    const [, subset = '', body] = match;
    const prop = name => (body.match(new RegExp(`${name}:\\s*([^;]+);`)) || [])[1]?.trim();
    const url = (body.match(/url\(([^)]+)\)/) || [])[1];
    if (!url) continue;
    faces.push({ subset: subset.replace(/[[\]]/g, ''), style: prop('font-style') ?? 'normal',
      weight: prop('font-weight') ?? '400', url, unicodeRange: prop('unicode-range') });
  }
  return faces;
}

async function main() {
  mkdirSync(FILES_DIR, { recursive: true });
  for (const stale of readdirSync(FILES_DIR)) unlinkSync(join(FILES_DIR, stale));
  const rules = [];
  let count = 0;
  for (const { family, weights } of FAMILIES) {
    const query = `family=${family.replace(/ /g, '+')}:wght@${weights.join(';')}&display=swap`;
    const faces = parseFaces(await fetchText(`https://fonts.googleapis.com/css2?${query}`));
    if (!faces.length) throw new Error(`no faces for ${family}`);
    for (const [index, face] of faces.entries()) {
      const name = `${slug(family)}-${face.weight}-${slug(face.subset) || index}.woff2`;
      writeFileSync(join(FILES_DIR, name), await fetchBytes(face.url));
      count++;
      rules.push(`@font-face {\n  font-family: '${family}';\n  font-style: ${face.style};\n  font-weight: ${face.weight};\n  font-display: swap;\n  src: url('./files/${name}') format('woff2');`
        + (face.unicodeRange ? `\n  unicode-range: ${face.unicodeRange};` : '') + '\n}');
    }
    console.log(`${family}: ${faces.length} faces`);
  }
  const root = FAMILIES.map(({ family, variable }) => `  ${variable}: '${family}';`).join('\n');
  const header = `/* Generated by scripts/fetch-fonts.mjs (${new Date().toISOString().slice(0, 10)}). Self-hosted HUD typefaces:\n`
    + FAMILIES.map(({ family, weights }) => ` * ${family} ${weights.join('/')}`).join('\n')
    + `\n * Do not edit by hand; re-run the script to refresh. */\n`;
  writeFileSync(join(OUT_DIR, 'fonts.css'), `${header}:root {\n${root}\n}\n\n${rules.join('\n\n')}\n`);
  console.log(`wrote ${count} files and ${OUT_DIR}/fonts.css`);
}

main().catch(error => { console.error(error); process.exit(1); });
